# ./docker-compose.yml

version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: thesis
      MYSQL_DATABASE: thesis
    volumes:
      - ./extra/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

  web:
    build: .
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./webserver/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
        - app-network


networks:
  app-network:
    driver: bridge
